import type { Medication, Patient } from "./types.js"

export const mockPatients: Record<string, Patient> = {
  ABC1234: {
    nhi: "ABC1234",
    name: {
      title: "Mr",
      firstName: "John",
      lastName: "Doe",
    },
    dateOfBirth: "1985-06-15",
    gender: "male",
    address: {
      line1: "123 Main Street",
      line2: "Apartment 4B",
      suburb: "Newmarket",
      city: "Auckland",
      region: "Auckland",
      postcode: "1023",
      country: "NZ",
    },
    contactDetails: {
      phone: "+64 9 123 4567",
      mobile: "+64 21 987 6543",
      email: "john.doe@example.com",
    },
    emergencyContact: {
      name: "Jane Doe",
      relationship: "Wife",
      phone: "+64 21 555 0123",
    },
    ethnicGroup: "NZ European",
    preferredLanguage: "English",
  },
  DEF5678: {
    nhi: "DEF5678",
    name: {
      title: "Ms",
      firstName: "Maria",
      lastName: "Garcia",
    },
    dateOfBirth: "1990-03-22",
    gender: "female",
    address: {
      line1: "456 Queen Street",
      city: "Wellington",
      region: "Wellington",
      postcode: "6011",
      country: "NZ",
    },
    contactDetails: {
      phone: "+64 4 456 7890",
      email: "maria.garcia@example.com",
    },
    ethnicGroup: "Latin American",
    preferredLanguage: "Spanish",
  },
  GHI9012: {
    nhi: "GHI9012",
    name: {
      title: "Dr",
      firstName: "Priya",
      lastName: "Patel",
    },
    dateOfBirth: "1978-11-08",
    gender: "female",
    address: {
      line1: "789 Papanui Road",
      suburb: "Papanui",
      city: "Christchurch",
      region: "Canterbury",
      postcode: "8052",
      country: "NZ",
    },
    contactDetails: {
      phone: "+64 3 789 0123",
      mobile: "+64 27 111 2233",
      email: "priya.patel@example.com",
    },
    ethnicGroup: "Indian",
    preferredLanguage: "English",
  },
}

export const mockMedications: Record<string, Medication[]> = {
  ABC1234: [
    {
      id: "med1",
      name: "Aspirin",
      genericName: "Acetylsalicylic acid",
      brandName: "Disprin",
      dosage: "100mg",
      frequency: "once daily",
      route: "oral",
      startDate: "2024-01-01",
      prescribingDoctor: "Dr. Smith",
      prescriptionDate: "2024-01-01",
      status: "active",
      indication: "Cardiovascular protection",
    },
    {
      id: "med2",
      name: "Metformin",
      genericName: "Metformin hydrochloride",
      dosage: "500mg",
      frequency: "twice daily",
      route: "oral",
      startDate: "2023-06-15",
      prescribingDoctor: "Dr. Jones",
      prescriptionDate: "2023-06-15",
      status: "active",
      indication: "Type 2 diabetes",
    },
    {
      id: "med3",
      name: "Paracetamol",
      genericName: "Acetaminophen",
      dosage: "500mg",
      frequency: "as needed",
      route: "oral",
      startDate: "2023-12-01",
      endDate: "2024-01-15",
      prescribingDoctor: "Dr. Brown",
      prescriptionDate: "2023-12-01",
      status: "discontinued",
      indication: "Pain relief",
    },
  ],
  DEF5678: [
    {
      id: "med4",
      name: "Levothyroxine",
      dosage: "75mcg",
      frequency: "once daily",
      route: "oral",
      startDate: "2023-03-01",
      prescribingDoctor: "Dr. Wilson",
      prescriptionDate: "2023-03-01",
      status: "active",
      indication: "Hypothyroidism",
    },
  ],
  GHI9012: [
    {
      id: "med5",
      name: "Lisinopril",
      dosage: "10mg",
      frequency: "once daily",
      route: "oral",
      startDate: "2023-08-01",
      prescribingDoctor: "Dr. Taylor",
      prescriptionDate: "2023-08-01",
      status: "active",
      indication: "Hypertension",
    },
  ],
}

