version: '3.8'

services:
  openhealth-api:
    build: .
    ports:
      - "8080:8080"  # Frontend (Cloud Run compatible)
      - "3000:3000"  # Central API (internal)
      - "3001:3001"  # DHB Service (internal) 
      - "3003:3003"  # Toniq Service (internal)
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    restart: unless-stopped
    
  # Service registration container - runs once to register providers
  register-services:
    image: curlimages/curl:latest
    depends_on:
      openhealth-api:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for services to be ready...' &&
        sleep 5 &&
        echo 'Registering DHB service...' &&
        curl -X POST http://openhealth-api:3000/register 
          -H 'Content-Type: application/json' 
          -d '{\"providerId\": \"dhb-auckland\", \"baseUrl\": \"http://localhost:3001/api/v1\"}' &&
        echo 'Registering Toniq service...' &&
        curl -X POST http://openhealth-api:3000/register 
          -H 'Content-Type: application/json' 
          -d '{\"providerId\": \"toniq-medications\", \"baseUrl\": \"http://localhost:3003/api/v1\"}' &&
        echo 'All services registered successfully!'
      "
    restart: "no"

networks:
  default:
    name: openhealth-network