module.exports = {
  apps: [
    {
      name: "frontend",
      script: "./frontend/node_modules/.bin/serve",
      args: "-s ./frontend/dist -l 8080",
      cwd: "/app",
      env: {
        NODE_ENV: "production",
      },
      instances: 1,
      exec_mode: "fork",
      restart_delay: 1000,
      max_restarts: 10,
      min_uptime: "10s",
    },
    {
      name: "central-api",
      script: "./central_api/dist/index.js",
      cwd: "/app",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
        DATABASE_URL: process.env.DATABASE_URL || "postgresql://openhealth_user:openhealth_password@postgres:5432/openhealth",
        DB_HOST: process.env.DB_HOST || "postgres",
        DB_PORT: process.env.DB_PORT || 5432,
        DB_NAME: process.env.DB_NAME || "openhealth",
        DB_USER: process.env.DB_USER || "openhealth_user",
        DB_PASSWORD: process.env.DB_PASSWORD || "openhealth_password",
      },
      instances: 1,
      exec_mode: "fork",
      restart_delay: 1000,
      max_restarts: 10,
      min_uptime: "10s",
    },
    {
      name: "dhb-api",
      script: "./DHB/dist/index.js",
      cwd: "/app",
      env: {
        NODE_ENV: "production",
        PORT: 3001,
        CENTRAL_API_URL: "http://localhost:3000",
        DATABASE_URL: process.env.DATABASE_URL || "postgresql://openhealth_user:openhealth_password@postgres:5432/openhealth",
        DB_HOST: process.env.DB_HOST || "postgres",
        DB_PORT: process.env.DB_PORT || 5432,
        DB_NAME: process.env.DB_NAME || "openhealth",
        DB_USER: process.env.DB_USER || "openhealth_user",
        DB_PASSWORD: process.env.DB_PASSWORD || "openhealth_password",
      },
      instances: 1,
      exec_mode: "fork",
      restart_delay: 1000,
      max_restarts: 10,
      min_uptime: "10s",
    },
    {
      name: "toniq-api",
      script: "./Toniq/dist/index.js",
      cwd: "/app",
      env: {
        NODE_ENV: "production",
        PORT: 3003,
        CENTRAL_API_URL: "http://localhost:3000",
        DATABASE_URL: process.env.DATABASE_URL || "postgresql://openhealth_user:openhealth_password@postgres:5432/openhealth",
        DB_HOST: process.env.DB_HOST || "postgres",
        DB_PORT: process.env.DB_PORT || 5432,
        DB_NAME: process.env.DB_NAME || "openhealth",
        DB_USER: process.env.DB_USER || "openhealth_user",
        DB_PASSWORD: process.env.DB_PASSWORD || "openhealth_password",
      },
      instances: 1,
      exec_mode: "fork",
      restart_delay: 1000,
      max_restarts: 10,
      min_uptime: "10s",
    },
  ],
}

